---
- name: "Upload Config | {{ logrotate_name }} "
  template:
    src: etc/ntp.conf
    dest: "/etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - template-configuration
    - ntp

